version: "3"

services:
  front:
    container_name: DSF-INTERLUP-FRONT-DEV
    image: dsf-interlup-front-dev
    env_file:
      - ./.env
    build: .
    ports:
      - 80:80
    restart: unless-stopped
